/**
 * 
 * Canvas.java
 * <br>
 * Class {@code Canvas} mendefinisikan tempat menggambarkan kura-kura. 
 * <br><br>
 * Untuk keperluan Tugas 1, anda tidak perlu untuk memodifikasi file ini.
 * 
 * @author  DPBO 2008 @ Fasilkom UI
 * 
 */ 


public class Canvas extends javax.swing.JPanel {
    private Kurakura kurakura;
    /** Creates new form Canvas */
    
    
    /**
     * Constuctor ini membuat canvas tanpa parameter kurakura
     * sehingga object kurakura harus dibuat terlebih dahulu.
     * Bagi object lain yang hendak mengambil reference, dapat
     * menggunakan method {@code getKurakura()}.
     */
    public Canvas() {
        kurakura = new Kurakura();
        initComponents();        
    }
    
    /**
     * Constuctor ini membuat canvas dengan memberikan parameter berupa
     * reference atas kurakura yang akan digambarkan pada canvas.
     * 
     * @param k bertipe Kurakura.
     */
    public Canvas(Kurakura k) {
        kurakura = k;
        initComponents();        
    }    
   
    /**
     * Method ini memberikan reference kura-kura yang berada dalam canvas.
     * 
     * @return object kurakura yang terdapat dalam canvas.
     */
    public Kurakura getKurakura(){
        return kurakura;
    }
    /** 
     * Method ini mengoverride method milik parent. 
     * Keyword Override dibutuh untuk memastikan bahwa
     * penamaan tidak keliru dan memastikan bahwa benar mengoverride.
     * 
     */
    @Override
    public void paintComponent(java.awt.Graphics g){
        super.paintComponent(g);
        setBackground(new java.awt.Color(51, 0, 204));
        kurakura.draw((java.awt.Graphics2D) g);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
